server:
  name: "SuperAugment"
  version: "1.0.0"
  description: "MCP Server for VS Code Augment"
  
logging:
  level: "info"
  format: "json"
  max_file_size: "5MB"
  max_files: 5
  
tools:
  default_persona: null
  timeout: 30000  # 30 seconds
  max_concurrent: 10
  
analysis:
  default_depth: "detailed"
  max_file_size: "10MB"
  supported_languages:
    - "javascript"
    - "typescript"
    - "python"
    - "java"
    - "go"
    - "rust"
    - "cpp"
    - "csharp"
    
build:
  default_environment: "development"
  enable_optimization: false
  parallel_builds: true
  
security:
  scan_timeout: 60000  # 60 seconds
  max_scan_depth: "standard"
  enable_dependency_check: true
  
testing:
  default_framework: "jest"
  enable_coverage: false
  parallel_execution: true
  coverage_threshold: 80
  
deployment:
  default_strategy: "rolling"
  enable_health_checks: true
  rollback_on_failure: true
  
resources:
  cache_duration: 3600  # 1 hour
  max_resource_size: "50MB"
  
prompts:
  max_context_length: 8000
  enable_persona_context: true
